disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "utkarshkrsingh"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "skinmc-avatar.png"
secondaryLogo = "skinmc-avatar.png"
description = ""

[[params.author.links]]
email = "mailto:utkarsh.isa.dev@gmail.com"

[[params.author.links]]
github = "https://github.com/utkarshkrsingh/"

[[params.author.links]]
linkedin = "https://www.linkedin.com/in/utkarshkrsingh1103/"

[[params.author.links]]
reddit = "https://www.reddit.com/user/utkarshkrsingh/"

["params.author"]
name = "Utkarsh Kumar Singh"
image = "profile.png"
headline = "Backend Developer | Linux Enthusiast | Learning Go"
