[[main]]
none = "none"

[[main]]
name = "Blogs"
pageRef = "blogs"
identifier = "Ff2vMAyUj9"
weight = 9_999

[[main]]
name = "Projects"
pageRef = "projects"
identifier = "wIVMuCjLdJ"
weight = 9_999

[[footer]]
none = "none"
